name: network_performance
dependencies: []
automanagednamespaces: 0
namespace:
  number: 1
  prefix: test-ysef28
  deletestalenamespaces: false
  deleteautomanagednamespaces: true
  enableexistingnamespaces: false
  deletenamespacetimeout: 600000000000
steps:
- phases: []
  measurements:
  - method: NetworkPerformanceMetrics
    params:
      action: start
      duration: 10s
      numberOfClients: 1
      numberOfServers: 1
      protocol: TCP
    identifier: NetworkPerformanceMetrics
    instances: []
  module:
    path: ""
    params: {}
  name: Start network performance measurement
- phases: []
  measurements:
  - method: NetworkPerformanceMetrics
    params:
      action: gather
    identifier: NetworkPerformanceMetrics
    instances: []
  module:
    path: ""
    params: {}
  name: Gather network performance measurement
tuningsets: []
chaosmonkey:
  nodefailure: null
  excludednodes: {}
